### ISSUE TITLE
Instascale Epic

### ISSUE THREAD

**Issue by VanillaSpoon** [project-codeflare/instascale#174]
These are some focus issues for instascale, bringing them together as I feel there are higher priority:

## Issues

- [ ] https://github.com/project-codeflare/instascale/issues/80
- [ ] https://github.com/project-codeflare/instascale/issues/143
- [ ] https://github.com/project-codeflare/instascale/issues/172
- [ ] https://github.com/project-codeflare/instascale/issues/163
- [ ] https://github.com/project-codeflare/instascale/issues/173
- [ ] https://github.com/project-codeflare/instascale/issues/73

I also believe after these changes, a refactor of instascale may be on the table, to reduce the duplication between machine types, and allow for further extension. 

I'm open to any discussions about adding/removing priority issues if there are any suggestions also :)

**Comment by asm582** [comment]
Thanks, do we know how we plan to test the above issues?
